name: app_ia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  record: ^5.1.2
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - scripts/
